INSERT INTO COURSE(id,NAME,AUTHOR) VALUES(10001,'LearnJava','Anuj');
INSERT INTO COURSE(ID,NAME,AUTHOR) VALUES(10002,'LearnAngular','Prince');
INSERT INTO COURSE(ID,NAME,AUTHOR) VALUES(10003,'LearnReact','Aman');

